name: Auto Hexo

on: push

permissions:
  id-token: write
  contents: write

jobs:
  Work:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Checkout source
      uses: actions/checkout@v4
      with:
        ref: source
        path: 'blog-source-ws'

    - name: Setup Hexo
      run: |
        npm install -g hexo-cli@4.3.0
        cd blog-source-ws
        npm install

    - name: Checkout master
      uses: actions/checkout@v4
      with:
        ref: master
        path: 'blog-source-ws/public'

    - name: Regenerate and Deploy
      run: |
        export TZ='Asia/Shanghai'
        cd blog-source-ws/public
        ls -a | egrep -v '^\.{1,2}$' | egrep -v .git | xargs rm -rf
        cd ..
        hexo g
        cd public
        git config --local user.name "ProgCZ"
        git config --local user.email "${{ secrets.PERSONAL_EMAIL_ADDRESS }}"
        git add -A
        git commit -m "update at `date '+%Y-%m-%d %H:%M:%S'`"
        git push origin master

    - name: Login Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Clear Azure Storage
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az storage blob delete-batch --account-name progczcomstorage --auth-mode login -s '$web'

    - name: Upload to Azure Storage
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az storage blob upload-batch --account-name progczcomstorage --auth-mode login -d '$web' -s blog-source-ws/public --pattern "[!.]*" --overwrite true

    - name: Purge Azure CDN
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az cdn endpoint purge -g blog-rg -n progczcom --profile-name progczcom-cdn --content-paths "/*"

    - name: Logout Azure
      run: |
        az logout
      if: always()
