name: Auto Hexo

on: push

permissions:
  id-token: write

jobs:
  Work:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Checkout source
      uses: actions/checkout@v2
      with:
        ref: source
        path: 'blog-source-ws'

    - name: Setup Hexo
      run: |
        npm install -g hexo-cli@4.3.0
        cd blog-source-ws
        npm install

    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master
        path: 'blog-source-ws/public'

    - name: Regenerate and Deploy
      run: |
        export TZ='Asia/Shanghai'
        cd blog-source-ws/public
        ls -a | egrep -v '^\.{1,2}$' | egrep -v .git | xargs rm -rf
        cd ..
        hexo g
        cd public
        git config --local user.name "ProgCZ"
        git config --local user.email "${{ secrets.PERSONAL_EMAIL_ADDRESS }}"
        git add -A
        git commit -m "update at `date '+%Y-%m-%d %H:%M:%S'`"
        git push origin master

    - name: Login Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Clear Azure Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name progczcomstorage --auth-mode login -s '$web'

    - name: Upload to Azure Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name progczcomstorage --auth-mode login -d '$web' -s blog-source-ws/public --pattern "[!.]*" --overwrite true

    - name: Logout Azure
      run: |
        az logout
      if: always()

    - name: Sleep
      run: |
        sleep 30

    - name: Ping Google
      uses: wei/curl@v1
      with:
        args: http://www.google.com/ping?sitemap=https://progcz.com/sitemap.xml
