name: Deploy Azure Storage

on: page_build

jobs:
  Work:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to Azure Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name progczcomstorage --auth-mode key -d '$web' -s .

    - name: Logout
      run: |
        az logout
      if: always()
